python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_1_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_2_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_3_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_4_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_5_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_6_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_7_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_8_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_9_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_10_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_11_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_12_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_13_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_14_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_15_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_16_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_17_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_18_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_19_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_20_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_21_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_22_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_23_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_24_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_25_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_26_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_27_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_28_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_29_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_30_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_31_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_32_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_33_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_34_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_35_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_36_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_37_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_38_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_39_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_40_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_41_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_42_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_43_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_44_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_45_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_46_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_47_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_48_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_49_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_50_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_51_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_52_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_53_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_54_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_55_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_56_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_57_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_58_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_59_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_60_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_61_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_62_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_63_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_64_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_65_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_66_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_67_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_68_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_69_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_70_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_71_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_72_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_73_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_74_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_75_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_76_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_77_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_78_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_79_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_80_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_81_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_82_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_83_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_84_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_85_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_86_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_87_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_88_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_89_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_90_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_91_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_92_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_93_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_94_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_95_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_96_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_97_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_98_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_99_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_100_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_101_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_102_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_103_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_104_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_105_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_106_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_107_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_108_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_109_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_110_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_111_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_112_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_113_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_114_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_115_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_116_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_117_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_118_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_119_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_120_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_121_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_122_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_123_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_124_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_125_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_126_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_127_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_128_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_129_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_130_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_131_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_132_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_133_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_134_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_135_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_136_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_137_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_138_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_139_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_140_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_141_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_142_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_143_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_144_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_145_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_146_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_147_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_148_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_149_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_150_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_151_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_152_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_153_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_154_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_155_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_156_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_157_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_158_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_159_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_160_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_161_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_162_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_163_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_164_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_165_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_166_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_167_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_168_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_169_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_170_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_171_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_172_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_173_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_174_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_175_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_176_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_177_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_178_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_179_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_180_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_181_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_182_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_183_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_184_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_185_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_186_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_187_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_188_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_189_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_190_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_191_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_192_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_193_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_194_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_195_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_196_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_197_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_198_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_199_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_200_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_201_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_202_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_203_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_204_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_205_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_206_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_207_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_208_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_209_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_210_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_211_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_212_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_213_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_214_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_215_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_216_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_217_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_218_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_219_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_220_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_221_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_222_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_223_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_224_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_225_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_226_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_227_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_228_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_229_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_230_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_231_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_232_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_233_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_234_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_235_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_236_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_237_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_238_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_239_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_240_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_241_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_242_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_243_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_244_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_245_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_246_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_247_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_248_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_249_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_250_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_251_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_252_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_253_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_254_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_255_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_256_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_257_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_258_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_259_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_260_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_261_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_262_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_263_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_264_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_265_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_266_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_267_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_268_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_269_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_270_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_271_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_272_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_273_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_274_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_275_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_276_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_277_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_278_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_279_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_280_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_281_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_282_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_283_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_284_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_285_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_286_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_287_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_288_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_289_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_290_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_291_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_292_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_293_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_294_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_295_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_296_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_297_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_298_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_299_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_300_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_301_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_302_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_303_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_304_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_305_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_306_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_307_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_308_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_309_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_310_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_311_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_312_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_313_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_314_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_315_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_316_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_317_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_318_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_319_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_320_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_321_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_322_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_323_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_324_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_325_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_326_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_327_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_328_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_329_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_330_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_331_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_332_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_333_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_334_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_335_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_336_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_337_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_338_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_339_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_340_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_341_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_342_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_343_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_344_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_345_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_346_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_347_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_348_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_349_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_350_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_351_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_352_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_353_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_354_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_355_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_356_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_357_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_358_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_359_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_360_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_361_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_362_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_363_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_364_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_365_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_366_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_367_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_368_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_369_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_370_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_371_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_372_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_373_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_374_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_375_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_376_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_377_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_378_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_379_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_380_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_381_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_382_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_383_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_384_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_385_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_386_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_387_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_388_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_389_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_390_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_391_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_392_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_393_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_394_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_395_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_396_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_397_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_398_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_399_dataset2/ &
python3.7 bioProject.py markfolder /home/mona/Desktop/Localization/dataset/test_400_dataset2/ &
